# Factorisation de Cholesky

- Soit $A \in M{n,n}$ où $A$ est respectivement strictement définie positive alors il existe une matrice $C$ triangulaire inférieure telle que $A = CC^t$
- En plus cette décomposition de Cholesky est unique si et seulement si les coefficients diagonaux de $C$ sont positifs: $C_{i,i} \ge 0$ avec $\forall i=1, ..., n$

In [8]:
# librairies python :
import numpy as np
from time import time

In [9]:
# algo :
def Cholesky(A):
    n = len(A)
    C = np.zeros((n,n))
    C[0,0] = np.sqrt(A[0,0])
    
    for i in range(1, n):
        C[i,0] = A[i,0] / C[0,0]
        
    for i in range(1, n-1):
        C[i,i] = np.sqrt(A[i,i] - sum(C[i,k] * C[i,k] for k in range(i)))
        
        for j in range(i+1, n):
            C[j,i] = (A[j,i] - sum(C[j,k] * C[i,k] for k in range(i))) / C[i,i]
    
    C[n-1,n-1] = np.sqrt(A[n-1, n-1] - sum(C[n-1,k] * C[n-1,k] for k in range(n)))

    return C

### Test :

In [12]:
A = np.array([[1,1,1],[1,5,7],[1,7,26]])

start = time()
C = Cholesky(A)
print("C = \n{}".format(C))
print("Time = {}".format(time() - start))

C = 
[[1. 0. 0.]
 [1. 2. 0.]
 [1. 3. 4.]]
Time = 0.001010894775390625


### Avec la fonction de numpy :

In [13]:
start = time()
C_numpy = np.linalg.cholesky(A)
print("C = \n{}".format(C))
print("Time = {}".format(time() - start))

C = 
[[1. 0. 0.]
 [1. 2. 0.]
 [1. 3. 4.]]
Time = 0.0010180473327636719
