# Méthodes exactes (Directes) pour la résolution des systèmes linéaires :

## Factorisation QR :

- Soit $A \in M_{n,n}$ une matrice, alors il existe une matrice orthogonale $Q$, et une matrice triangulaire supérieure $R$ telles que : $A = QR$

- En plus si $A$ est inversible, la décomposition $QR$ est unique.

- Le système $Ax = b$ devient $QRx = b$, et par changement de variable ($Rx = y$), on obtient le système linéaire suivant :
1. $ Qy = b $ $\Longleftrightarrow$ $ y = Q^tb $
2. $ Rx = y $

- La résolution ce fait avec l'algorithme de la matrice triangulaire supérieure.
- Puis utilisation de Gram-schmidt

### Procédé de Gram-Schimdt :

- On met la matrice $A$ sous la forme : $A = (a_1, a_2, ..., a_n)$ avec $a_i$ un vecteur colonne $\forall i = 1,...,n $
- Principe : Base quelconque de $R^n$ $\longrightarrow$ Base orthonormée.
- Calcul de $Q$ :
$$ u_1 = a_1 \longrightarrow e_1 = \frac{u_1}{\lvert\lvert u_1 \rvert\rvert}$$
$$ u_k = a_k - \sum_{i=1}^{k-1} <a_k|e_i>e_i \longrightarrow e_k = \frac{u_k}{\lvert\lvert u_k \rvert\rvert}$$

- Alors la famille {$e_1, e_2, ..., e_n$} est une base orthonormée.
- Et la décomposition $QR$ est obtenue par : 
$$ A = (a_1|a_2|...|a_n) = (e_1 e_2 ... e_n) \begin{vmatrix} <a_1,e_1> & <a_2,e_1> & ... & <a_n,e_1>\\  0     & <a_2,e_2> & ...& <a_n,e_2>\\ ...    &     0     & ... &    ...   \\   0     &     0     & ... & <a_n,e_n>\\ \end{vmatrix} $$

## Implémentation :

In [35]:
# librairie python :
import numpy as np
from time import time

In [67]:
def decompoQR(A):
    n = len(A)
    Q = np.zeros((n,n))
    R = np.zeros((n,n))
    U = np.zeros((n,n))
    
    U[0] = A[0]
    Q[0] = U[0] / np.linalg.norm(U[0])
    
    # calcul de la matrice Q orthogonale :
    for i in range(1,n):
        somme = 0
        for k in range(i):
            R[k,i] = np.dot(A[i], Q[k])
            somme += np.dot(R[k,i], Q[k])
        U[i] = A[i]  - somme
        Q[i] = U[i] / np.linalg.norm(U[i])
        
    # Calcul matrice R :
    for i in range(n):
        R[i,i] = np.dot(A[i], Q[i])
    
    return Q.T, R

## Test :

In [68]:
A = np.array([[1,1,0],[1,0,1],[0,1,1]])

start = time()
Q,R = decompoQR(A.T)
print("Q = \n{}".format(Q))
print("R = \n{}".format(R))
print("Time = {}".format(time() - start))

Q = 
[[ 0.70710678  0.40824829 -0.57735027]
 [ 0.70710678 -0.40824829  0.57735027]
 [ 0.          0.81649658  0.57735027]]
R = 
[[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 0.40824829]
 [0.         0.         1.15470054]]
Time = 0.0010445117950439453


## Factorisation QR avec Numpy :

In [69]:
start = time()
Q, R = np.linalg.qr(A)
print("Q = \n{}".format(Q))
print("R = \n{}".format(R))
print("Time = {}".format(time() - start))

Q = 
[[-0.70710678  0.40824829 -0.57735027]
 [-0.70710678 -0.40824829  0.57735027]
 [-0.          0.81649658  0.57735027]]
R = 
[[-1.41421356 -0.70710678 -0.70710678]
 [ 0.          1.22474487  0.40824829]
 [ 0.          0.          1.15470054]]
Time = 0.013729572296142578
