# Decomposition LU

- Décomposition d'une matrice *carrée*, inversible, A en une matrice triangulaire inférieure L telle que $L_{i,i} = 1$ pour	$\forall i = 1, ..., n$, et en une matrice triangulaire supérieure $U$ telle que $A = LU$

- La matrice $L$ : $L_{i,j} = 0$ avec $i < j$

- La matrice $U$ : $U_{i,j} = 0$ avec $i > j$

## Méthode :

- $L_{1,1} = 1$

- Pour $j$ de 1 à $n$ :
$$ U_{1,j} = a_{1,j} $$

- Pour $i$ de 2 à $n$ :
$$ L_{i,1} = \frac{a_{i,1}}{U_{1,1}} $$

- Pour $i$ de 2 à $n$ faire :
$$ L_{i,i} = 1 $$
$$ U_{i,i} = a_{i,i} - \sum_{k=1}^{i-1} L_{i,k}U_{k,i}	 $$

- Dans la boucle précédente, pour $j = i + 1$ à $n$, faire :
$$ U_{i,j} = (a_{i,j} - \sum_{k=1}^{i-1} L_{i,k}U_{k,j}) $$

$$ L_{j,i} = (a_{j,i} - \sum_{k=1}^{i-1} L_{j,k}U_{k,i}) \frac{1}{U_{i,i}} $$

## Implémentation :

In [1]:
# librairies python :
import numpy as np
from time import time

In [2]:
def decompoLU(A):
    n = len(A)
    L = np.zeros((n,n))
    U = np.zeros((n,n))
    
    L[0,0] = 1
    for i in range(n):
        U[0,i] = A[0,i]
    
    for i in range(1, n):
        L[i,0] = A[i,0]/U[0,0]
        
    for i in range(1, n):
        L[i,i] = 1
        
        for j in range(i+1, n):
            s1 = sum(L[i,k] * U[k,j] for k in range(j))
            U[i,j] = (A[i,j] - s1)
            
        for j in range(1, i):
            s2 = sum(L[i,k] * U[k,j] for k in range(j))
            L[i,j] = (A[i,j] - s2)/U[j,j]

        
        s0 = sum(L[i,k] * U[k,i] for k in range(i))
        U[i,i] = A[i,i] - s0
            
    return (L,U)

## Tests

In [3]:
A = np.array([[3, 2, 1],
              [6, 6, 3],
              [-3, 6, 4]])


start = time()
(L, U) = decompoLU(A)
print("L = \n{}".format(L))
print("U = \n{}".format(U))
print("Time = {}".format(time() - start))

L = 
[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  4.  1.]]
U = 
[[3. 2. 1.]
 [0. 2. 1.]
 [0. 0. 1.]]
Time = 0.008914470672607422
