# Résolution d'un système par la méthode d'élimination de Gauss

Programme de résolution d'un système matriciel A.X = B où les matrices A et B sont données. On commence par déterminer un système équivalent A ' .X = B '  où A ' est une matrice triangulaire supérieure déterminée à partir de la matrice A, puis on calcul les valeurs (xn, xn-1, ..., x2, x1).

# Programme

In [1]:
import numpy as np

# Fonctions :
def Somme(i):
    z = 0
    for j in range((i+1), (N+1)):
        z = z + AT[i-1,j-1] * X[j-1, 0]
    return z

# données :
N = 4
A = np.array([ [2, -5, 1, 3],
               [4,  7, 8, 2],
               [3,  1, 1, 6],
               [4,  1, 7, 9] ], float)

B = np.array([ [5],
              [10],
               [2],
               [6] ], float)

X = np.zeros((N,1))
AT = A.copy()
BT = B.copy()

# Elimination de Gauss :
for k in range(0, (N-1)):
    for i in range((k+1), (N)):
        q = AT[i,k]/AT[k,k]
        BT[i,0] = BT[i,0] - q*BT[k,0]
        AT[i,k] = 0
        for j in range((k+1), (N)):
            AT[i,j] = AT[i,j] - q*AT[k,j]

            
# Résolution AT*X = B
X[N-1,0] = BT[N-1,0]/AT[N-1,N-1]
for i in range(N-1, 0, -1):
    X[i-1,0] = (1/AT[i-1,i-1])*(BT[i-1,0] - Somme(i))
    

# Résultats :
print("Matrice A = ")
print(A)
print("Matrice B = ")
print(B)
print("Matrice X = ")
print(X)

Matrice A = 
[[ 2. -5.  1.  3.]
 [ 4.  7.  8.  2.]
 [ 3.  1.  1.  6.]
 [ 4.  1.  7.  9.]]
Matrice B = 
[[ 5.]
 [10.]
 [ 2.]
 [ 6.]]
Matrice X = 
[[ 2.29699248]
 [-0.45363409]
 [ 0.71303258]
 [-0.85839599]]
