# Factorisation de Cholesky

- Soit $A \in M{n,n}$ où $A$ est respectivement strictement définie positive alors il existe une matrice C triangulaire inférieure telle que $A = CC^t$
- En plus cette décomposition de Cholesky est unique si et seulement si les coefficients diagonaux de $C$ sont positifs.

In [1]:
# library :
import numpy as np

In [19]:
# algo :
def Cholesky(A):
    n = len(A)
    C = np.zeros((n,n))
    C[0,0] = np.sqrt(A[0,0])
    
    for i in range(1, n):
        C[i,0] = A[i,0] / C[0,0]
        
    for i in range(1, n-1):
        C[i,i] = np.sqrt(A[i,i] - sum(C[i,k] * C[i,k] for k in range(i)))
        
        for j in range(i+1, n):
            C[j,i] = (A[j,i] - sum(C[j,k] * C[i,k] for k in range(i))) / C[i,i]
    
    C[n-1,n-1] = np.sqrt(A[n-1, n-1] - sum(C[n-1,k] * C[n-1,k] for k in range(n)))

    return C

### Test :

In [29]:
A = np.array([[1,1,1],[1,5,7],[1,7,26]])
A

array([[ 1,  1,  1],
       [ 1,  5,  7],
       [ 1,  7, 26]])

In [30]:
C = Cholesky(A)
C

array([[1., 0., 0.],
       [1., 2., 0.],
       [1., 3., 4.]])

### Avec la fonction de numpy :

In [31]:
np.linalg.cholesky(A)

array([[1., 0., 0.],
       [1., 2., 0.],
       [1., 3., 4.]])